import { useMemo, useState } from "react";
import { Bot, ChevronLeft, ChevronRight, Radio, Search, ShieldAlert, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { markets } from "@/lib/markets";

type AgentStatus = "Online" | "Idle" | "Offline";
const agents = Array.from({ length: 500 }, (_, i) => ({ id: i + 1, name: `Agent ${String(i + 1).padStart(3, "0")}`, source: i % 2 === 0 ? "Deriv" : "Quotex", pair: markets[i % markets.length].label, status: (i % 25 === 0 ? "Offline" : i % 10 === 1 ? "Idle" : "Online") as AgentStatus, latency: 12 + i * 7 % 79 }));

export default function AgentRegistry({ open, onOpenChange, online = true, live = false }: { open: boolean; onOpenChange: (open: boolean) => void; online?: boolean; live?: boolean }) {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("All");
  const [source, setSource] = useState("All");
  const [page, setPage] = useState(0);
  const [selectedId, setSelectedId] = useState(1);
  const registry = useMemo(() => live ? [] : agents.map(agent => ({ ...agent, status: online ? agent.status : "Offline" as AgentStatus })), [online, live]);
  const filtered = registry.filter(agent => (status === "All" || agent.status === status) && (source === "All" || source === agent.source) && `${agent.name} ${agent.pair}`.toLowerCase().includes(query.toLowerCase()));
  const pages = Math.max(1, Math.ceil(filtered.length / 10));
  const currentPage = Math.min(page, pages - 1);
  const selected = registry.find(agent => agent.id === selectedId);
  return open ? <Dialog open onOpenChange={onOpenChange}><DialogContent data-testid="agent-registry-dialog" showCloseButton={false} className="agent-registry-dialog"><DialogHeader><DialogTitle data-testid="agent-registry-title" className="agent-title"><Bot size={23} /> Agent control center <span>{live ? '500 slots' : '500'}</span></DialogTitle><DialogDescription data-testid="agent-registry-description">{live ? 'Configured capacity · source implementation and validation pending' : 'Simulated workers tracking reference-market & broker-style demo streams'}</DialogDescription></DialogHeader><Button data-testid="agent-registry-close" className="pair-picker-close" variant="ghost" size="icon-sm" aria-label="Close agent registry" onClick={() => onOpenChange(false)}><X size={17} /></Button>
    <div className="agent-summary" data-testid="agent-summary"><div><span>{live ? 'Implemented agents' : 'Total agents'}</span><strong data-testid="agent-count-total">{registry.length}</strong></div>{(["Online", "Idle", "Offline"] as const).map(value => <button key={value} data-testid={`agent-summary-${value.toLowerCase()}`} className={`agent-${value.toLowerCase()}`} onClick={() => { setStatus(value); setPage(0); }}><span>{value}</span><strong data-testid={`agent-count-${value.toLowerCase()}`}>{registry.filter(agent => agent.status === value).length}</strong></button>)}</div>
    <div className="agent-source-note" data-testid="agent-source-notice"><ShieldAlert size={15} /><span>{live ? <><b>500 configured slots · 0 implemented agents.</b> Specialized agent source is absent from the supplied repository. No live worker or accuracy is claimed.</> : <><b>MOCKED telemetry.</b> Online means a simulated worker, not a verified broker connection. Quotex source remains unverified.</>}</span></div>
    <div className="agent-heatmap" data-testid="agent-heatmap" aria-label={live ? 'No implemented live agents' : '500 simulated agent states'}>{registry.map(agent => <button key={agent.id} data-testid={`agent-cell-${agent.id}`} aria-label={`${agent.name}, ${agent.status}, ${agent.source} demo`} title={`${agent.name} · ${agent.status} · ${agent.source} (mock)`} className={`agent-cell agent-${agent.status.toLowerCase()} ${selectedId === agent.id ? "selected" : ""}`} onClick={() => setSelectedId(agent.id)} />)}</div>
    <div className="agent-selected" data-testid="agent-selected-details"><Bot size={18} />{selected ? <><strong data-testid="agent-selected-name">{selected.name}</strong><span data-testid="agent-selected-source">{selected.source} · {selected.source === "Quotex" ? "unverified demo" : "reference demo"}</span><span data-testid="agent-selected-pair">{selected.pair}</span><span className={`agent-state agent-${selected.status.toLowerCase()}`} data-testid="agent-selected-status">{selected.status}</span></> : <strong data-testid="agent-selected-name">No implemented live agents</strong>}</div>
    <div className="agent-filters"><div className="catalog-search"><Search size={15} /><Input data-testid="agent-search-input" aria-label="Search agents" placeholder="Search agent or pair…" value={query} onChange={event => { setQuery(event.target.value); setPage(0); }} /></div><select data-testid="agent-source-filter" aria-label="Filter agent source" value={source} onChange={event => { setSource(event.target.value); setPage(0); }}><option value="All">All sources</option><option>Deriv</option><option>Quotex</option></select><select data-testid="agent-status-filter" aria-label="Filter agent status" value={status} onChange={event => { setStatus(event.target.value); setPage(0); }}><option value="All">All states</option><option>Online</option><option>Idle</option><option>Offline</option></select></div>
    <div className="agent-table-wrap"><table className="agent-table" data-testid="agent-table"><thead><tr><th>Agent</th><th>Source</th><th>Tracking pair</th><th>Latency</th><th>Status</th></tr></thead><tbody>{filtered.slice(currentPage * 10, currentPage * 10 + 10).map(agent => <tr key={agent.id} data-testid={`agent-row-${agent.id}`}><td>{agent.name}</td><td>{agent.source}<small>{agent.source === "Quotex" ? "Unverified demo" : "Reference demo"}</small></td><td>{agent.pair}</td><td>{agent.status === "Online" ? `${agent.latency} ms` : "—"}</td><td><span className={`agent-state agent-${agent.status.toLowerCase()}`}><Radio size={10} />{agent.status}</span></td></tr>)}</tbody></table>{!filtered.length && <p data-testid="agent-empty-state" className="agent-empty-state">{live ? 'No implemented agents are available for live monitoring.' : 'No agents match your filters.'}</p>}</div>
    <div className="agent-pagination"><span data-testid="agent-result-count">{filtered.length} agents · Page {currentPage + 1} of {pages}</span><Button data-testid="agent-previous-page" variant="ghost" size="icon-sm" aria-label="Previous agent page" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}><ChevronLeft size={16} /></Button><Button data-testid="agent-next-page" variant="ghost" size="icon-sm" aria-label="Next agent page" disabled={currentPage + 1 >= pages} onClick={() => setPage(currentPage + 1)}><ChevronRight size={16} /></Button></div>
  </DialogContent></Dialog> : null;
}