import { useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { ArrowDown, ArrowLeft, ArrowUp, BarChart3, Bell, Bot, ChevronDown, CircleHelp, Clock3, History, LayoutDashboard, Minus, Plus, RotateCcw, ShieldCheck, Wallet, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Toaster } from "sonner";
import Brand from "@/components/terminal/Brand";
import MarketRail from "@/components/terminal/MarketRail";
import AgentRegistry from "@/components/terminal/AgentRegistry";
import CountryFlags from "@/components/terminal/CountryFlags";
import TradingChart from "@/components/terminal/TradingChart";
import { getMarket } from "@/lib/markets";
import { countdown, durationOptions, money, useDemoTrading } from "@/hooks/useDemoTrading";

export default function Trade() {
  const navigate = useNavigate();
  const [params] = useSearchParams();
  const [pairId, setPairId] = useState(() => getMarket(params.get("pair")).id);
  const [agentsOpen, setAgentsOpen] = useState(false);
  const [duration, setDuration] = useState(60);
  const [investment, setInvestment] = useState("10");
  const [percentMode, setPercentMode] = useState(false);
  const [pending, setPending] = useState(false);
  const [historyTab, setHistoryTab] = useState("Open");
  const [fundsDialog, setFundsDialog] = useState<"deposit" | "withdraw" | null>(null);
  const [fundsAmount, setFundsAmount] = useState("1000");
  const [helpOpen, setHelpOpen] = useState(false);
  const { account, now, error, message, busy, placeTrade, adjustFunds, reset } = useDemoTrading();
  const pair = getMarket(pairId);
  const stakeCents = percentMode ? Math.round(account.balanceCents * Number(investment) / 100) : Math.round(Number(investment) * 100);
  const validStake = Number.isSafeInteger(stakeCents) && stakeCents >= 100;
  const totalReturn = validStake ? stakeCents + Math.round(stakeCents * pair.payoutPercent / 100) : 0;
  const openTrades = account.trades.filter(t => t.status === "OPEN" || t.status === "PENDING");
  const completed = account.trades.filter(t => t.status !== "OPEN" && t.status !== "PENDING");
  const visibleTrades = historyTab === "Open" ? openTrades : completed;
  const chartTrade = openTrades.find(t => t.pairId === pair.id && t.status === "OPEN" && t.entryPrice !== null);
  const advanced = () => navigate(`/?pair=${encodeURIComponent(pair.id)}`);
  const adjustDuration = (step: number) => setDuration(durationOptions[Math.max(0, Math.min(durationOptions.length - 1, durationOptions.indexOf(duration) + step))]);
  const order = (direction: "UP" | "DOWN") => { placeTrade(pair.id, direction, stakeCents, duration, pending); setHistoryTab("Open"); };
  return <div data-testid="trade-screen" className="terminal-shell trade-screen">
    <Toaster position="bottom-right" richColors theme="dark" />
    <header data-testid="terminal-header" className="terminal-header"><Brand /><span data-testid="trade-mode-label" className="trade-mode-label">WEB TRADING PLATFORM</span><div className="flex-1" /><div className="panel-visibility-controls mode-controls"><Button data-testid="open-agents-button" className="panel-visibility-button" variant="ghost" onClick={() => setAgentsOpen(true)}><Bot size={16} /><span>Agents</span><b>500</b></Button><Button data-testid="advanced-mode-button" className="panel-visibility-button" variant="ghost" onClick={advanced}><LayoutDashboard size={16} /><span>Advanced</span></Button></div><button data-testid="trade-notification-button" aria-label="Demo platform information" className="notification-button" onClick={() => setHelpOpen(true)}><Bell size={17} /></button><button data-testid="demo-account-button" className="demo-account-button" onClick={() => setFundsDialog("deposit")}><Wallet size={19} /><span><small data-testid="demo-account-label">DEMO ACCOUNT</small><strong data-testid="demo-balance">{money(account.balanceCents)}</strong></span><ChevronDown size={14} /></button><Button data-testid="demo-deposit-button" className="demo-deposit-button" onClick={() => setFundsDialog("deposit")}><Plus size={17} /> Deposit</Button><Button data-testid="demo-withdraw-button" className="demo-withdraw-button" onClick={() => { setFundsAmount("100"); setFundsDialog("withdraw"); }}>Withdrawal</Button></header>
    <div className="terminal-body"><aside className="navigation-rail trade-navigation" data-testid="trade-navigation"><button data-testid="trade-nav-terminal" className="nav-button active" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><BarChart3 size={21} /><span>Trade</span></button><button data-testid="trade-nav-support" className="nav-button" onClick={() => setHelpOpen(true)}><CircleHelp size={21} /><span>Support</span></button><button data-testid="trade-nav-account" className="nav-button" onClick={() => setFundsDialog("deposit")}><Wallet size={21} /><span>Account</span></button><button data-testid="trade-nav-history" className="nav-button" onClick={() => { setHistoryTab("History"); document.getElementById("demo-trade-history")?.scrollIntoView({ block: "nearest", behavior: "smooth" }); }}><History size={21} /><span>History</span></button><button data-testid="trade-nav-agents" className="nav-button" onClick={() => setAgentsOpen(true)}><Bot size={21} /><span>Agents</span></button><button data-testid="trade-nav-advanced" className="nav-button" onClick={advanced}><ArrowLeft size={21} /><span>Advanced</span></button><button data-testid="trade-nav-help" className="trade-help-button" onClick={() => setHelpOpen(true)}>Help</button></aside>
      <main className="terminal-workspace"><MarketRail activePairId={pairId} onSelect={setPairId} />
        <div className="trade-main-layout" data-testid="trade-main-layout"><div className="trade-chart-column"><div className="market-sentiment" data-testid="demo-market-sentiment" title="Mock sentiment only"><span>72%</span><i /><b>28%</b></div><TradingChart key={pairId} pair={pair} online wallClock tradeMarker={chartTrade ? { price: chartTrade.entryPrice!, direction: chartTrade.direction } : undefined} /></div>
          <aside className="trade-order-panel" data-testid="trade-order-panel"><section className="order-entry"><div className="order-pair-heading" data-testid="order-pair-heading"><CountryFlags pairId={pair.id} /><strong>{pair.label}</strong><span data-testid="order-payout-percent">{pair.payout}</span></div><div className="pending-trade-control"><span>Pending trade</span><button data-testid="pending-trade-toggle" role="switch" aria-checked={pending} aria-label="Schedule demo trade for next minute" className={`pending-switch ${pending ? "enabled" : ""}`} onClick={() => setPending(!pending)}><i /></button></div>{pending && <p data-testid="pending-trade-note" className="pending-trade-note">Starts at the next local minute. Stake is reserved now.</p>}
          <fieldset className="order-input-box"><legend>Time</legend><button data-testid="duration-decrease" aria-label="Shorter expiry" onClick={() => adjustDuration(-1)} disabled={duration === durationOptions[0]}><Minus size={15} /></button><select data-testid="trade-duration-select" aria-label="Trade expiry duration" value={duration} onChange={event => setDuration(Number(event.target.value))}>{durationOptions.map(seconds => <option key={seconds} value={seconds} label={`00:${countdown(seconds)}`} />)}</select><button data-testid="duration-increase" aria-label="Longer expiry" onClick={() => adjustDuration(1)} disabled={duration === durationOptions[durationOptions.length - 1]}><Plus size={15} /></button></fieldset><span className="order-input-caption" data-testid="expiry-mode-caption">{duration === 5 ? "5-SECOND DEMO EXPIRY" : "FIXED EXPIRY TIME"}</span>
          <fieldset className="order-input-box"><legend>Investment {percentMode ? "(%)" : "($)"}</legend><button data-testid="investment-decrease" aria-label="Decrease investment" onClick={() => setInvestment(String(Math.max(1, (Number(investment) || 1) - 1)))}><Minus size={15} /></button><Input data-testid="trade-investment-input" type="number" min="1" step="1" aria-label="Demo investment" value={investment} onChange={event => setInvestment(event.target.value)} /><button data-testid="investment-increase" aria-label="Increase investment" onClick={() => setInvestment(String((Number(investment) || 0) + 1))}><Plus size={15} /></button></fieldset><button data-testid="investment-mode-toggle" className="order-input-caption" onClick={() => { setPercentMode(!percentMode); setInvestment(percentMode ? "10" : "1"); }}>{percentMode ? "SWITCH TO AMOUNT" : "SWITCH TO PERCENTAGE"}</button>
          <div className="order-return"><span>Payout</span><strong data-testid="trade-expected-return">{money(totalReturn)}</strong></div><div className="order-profit" data-testid="trade-expected-profit">Profit: {money(validStake ? totalReturn - stakeCents : 0)} <span>· demo only</span></div><Button data-testid="place-up-trade-button" className="place-trade-button place-up" disabled={busy} onClick={() => order("UP")}><span>Up</span><ArrowUp size={21} /></Button><Button data-testid="place-down-trade-button" className="place-trade-button place-down" disabled={busy} onClick={() => order("DOWN")}><span>Down</span><ArrowDown size={21} /></Button><p className="order-disclaimer" data-testid="trade-demo-disclaimer"><ShieldCheck size={12} /> Simulated trading · server-saved funds</p>{error && <p role="alert" data-testid="trade-error-message" className="trade-error-message">{error}</p>}{!error && message && <p role="status" data-testid="trade-action-message" className="trade-action-message">{message}</p>}</section>
          <section id="demo-trade-history" className="demo-trade-history" data-testid="demo-trade-history"><div className="trade-history-tabs"><button data-testid="open-trades-tab" aria-pressed={historyTab === "Open"} onClick={() => setHistoryTab("Open")}>Trades <b data-testid="open-trades-count">{openTrades.length}</b></button><button data-testid="completed-trades-tab" aria-pressed={historyTab === "History"} onClick={() => setHistoryTab("History")}><Clock3 size={14} /> History <b data-testid="completed-trades-count">{completed.length}</b></button></div><div className="demo-trade-list">{visibleTrades.length === 0 && <div data-testid="trade-history-empty" className="trade-history-empty"><History size={24} /><strong>{historyTab === "Open" ? "No active trades" : "No completed trades"}</strong><p>Choose a pair, set an investment,<br />and place a demo Up or Down trade.</p></div>}{visibleTrades.map(trade => { const market = getMarket(trade.pairId); const active = trade.status === "OPEN" || trade.status === "PENDING"; const remaining = Math.ceil(((trade.status === "PENDING" ? trade.startsAt : trade.expiresAt) - now) / 1000); return <article key={trade.id} className={`demo-trade-row result-${trade.status.toLowerCase()}`} data-testid={`demo-trade-${trade.id}`}><div><CountryFlags pairId={trade.pairId} /><strong data-testid={`trade-pair-${trade.id}`}>{market.label}</strong><span data-testid={`trade-countdown-${trade.id}`}>{active ? countdown(remaining) : trade.status}</span></div><div><span className={trade.direction === "UP" ? "text-positive" : "text-negative"} data-testid={`trade-direction-${trade.id}`}>{trade.direction === "UP" ? "↑" : "↓"} {money(trade.stakeCents)}</span><span data-testid={`trade-status-${trade.id}`}>{active ? trade.status : money(trade.creditCents)}</span></div><small data-testid={`trade-prices-${trade.id}`}>{trade.status === "PENDING" ? "Reserved · waiting for scheduled start" : `Entry ${trade.entryPrice?.toFixed(market.precision)}${trade.exitPrice !== null ? ` → ${trade.exitPrice.toFixed(market.precision)}` : " · demo position"}`}</small></article>; })}</div><button data-testid="reset-demo-account-button" className="reset-demo-account" onClick={reset}><RotateCcw size={12} /> Reset demo account</button></section></aside>
        </div><footer className="terminal-footer" data-testid="terminal-footer"><span data-testid="prototype-disclaimer"><span className="tiny-dot" /> MASTER CANDLE · MOCKED MARKET DATA · NO REAL TRADES</span><span>Reference catalog · broker availability unverified</span></footer>
      </main></div>
    <AgentRegistry open={agentsOpen} onOpenChange={setAgentsOpen} live />
    {fundsDialog !== null && <Dialog open onOpenChange={open => { if (!open) setFundsDialog(null); }}><DialogContent className="demo-funds-dialog" data-testid="demo-funds-dialog" showCloseButton={false}><DialogHeader><DialogTitle data-testid="demo-funds-title">{fundsDialog === "deposit" ? "Add demo funds" : "Remove demo funds"}</DialogTitle><DialogDescription data-testid="demo-funds-description">Virtual balance only. No payment, bank account or real withdrawal.</DialogDescription></DialogHeader><Button data-testid="demo-funds-close" className="pair-picker-close" variant="ghost" size="icon-sm" aria-label="Close demo funds" onClick={() => setFundsDialog(null)}><X size={16} /></Button><label htmlFor="demo-funds-amount">Amount (USD)</label><Input id="demo-funds-amount" data-testid="demo-funds-amount" type="number" min="1" value={fundsAmount} onChange={event => setFundsAmount(event.target.value)} />{error && <p data-testid="demo-funds-error" role="alert" className="trade-error-message">{error}</p>}<Button data-testid="confirm-demo-funds-button" disabled={busy} onClick={async () => { if (fundsDialog && await adjustFunds(fundsDialog, Math.round(Number(fundsAmount) * 100))) setFundsDialog(null); }}>{fundsDialog === "deposit" ? "Add virtual funds" : "Remove virtual funds"}</Button></DialogContent></Dialog>}
    {helpOpen && <Dialog open onOpenChange={setHelpOpen}><DialogContent className="demo-funds-dialog" data-testid="trade-help-dialog" showCloseButton={false}><DialogHeader><DialogTitle data-testid="trade-help-title">Practice with Master Candle</DialogTitle><DialogDescription data-testid="trade-help-description">Virtual-money simulation with a server-saved account.</DialogDescription></DialogHeader><Button data-testid="trade-help-close" className="pair-picker-close" variant="ghost" size="icon-sm" aria-label="Close demo help" onClick={() => setHelpOpen(false)}><X size={16} /></Button><p data-testid="trade-help-instructions">Demo funds and trade history are saved on the server for this browser session. Pending trades start at the next minute. Account reset archives previous trades.</p><p data-testid="trade-help-warning">Quotes, payouts and results are simulated. No real money or broker execution. Agent implementations remain unavailable.</p></DialogContent></Dialog>}
  </div>;
}